config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :categories do
    resources :expenses
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  before_destroy :delete_associated_expenses
  belongs_to :user
  has_many :expenses
  has_one_attached :icon

  validates :name, presence: true
  validates :icon, presence: true

  private

  def delete_associated_expenses
    expenses.destroy_all
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :category

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable,
         :omniauthable

  has_many :categories, dependent: :destroy
  has_many :expenses, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show destroy]

  def index
    @categories = current_user.categories.includes(:icon_attachment)
    @expenses = Expense.where(category: @categories).order(created_at: :desc)
  end

  def show
    @category_expenses = @category.expenses.order(created_at: :desc)
    @total_amount = @category_expenses.sum(:amount)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to root_path, notice: 'Successfully created.'
    else
      render :new
    end
  end

  def destroy
    if @category.destroy
      redirect_to root_path, notice: 'Successfully deleted.'
    else
      redirect_to root_path, alert: 'Failed to delete category.'
    end
  end

  private

  def set_category
    @category = current_user.categories.find(params[:id]) if params[:id].present?

    return unless @category.nil?

    redirect_to root_path, alert: 'Category not found.'
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @expenses = @category.expenses.order(created_at: :desc)
  end

  def new
    @category = current_user.categories.find_by(id: params[:category_id])

    unless @category
      redirect_to root_path, alert: 'Category not found.'
      return
    end

    @expense = @category.expenses.build
  end

  def create
    @expense = current_user.expenses.build(expense_params)

    if @expense.save
      redirect_to category_path(@expense.category), notice: 'Successfully created.'
    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
    <% if category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
  
        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.label :icon, style: "display: block" %>
      <%= form.text_field :icon %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container mt-4">
  <div class="category-total-cost">
    <h3 class="total-title">Total cost for all categories</h3>
    <h3 class="total-cost">$<%= @expenses.sum(:amount) %></h3>
  </div>

  <div class="row">
    <% @categories.each do |category| %>
      <div class="col-12 mb-4">
        <div class="card">
          <div class="card-body d-flex align-items-center">
            <div class="col-4">
              <%= link_to category_path(category), class: "category-link d-flex align-items-center" do %>
                <%= image_tag category.icon, class: "category-img", alt: "#{category.name} icon" %>
                <div class="name-expense ms-3">
                  <h3 class="card-title"><%= category.name %></h3>
                  <p class="card-text category-date"><%= category.created_at.strftime('%d %b, %Y') %></p>
                </div>
              <% end %>
            </div>
            <div class="col-8 text-end">
              <div class="amount-del-div ms-auto">
                <p class="card-text amount">$<%= category.expenses.sum(:amount) %></p>
                <%= button_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', title: 'Delete Category' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="add-category-div text-center mt-4">
    <%= link_to "Add a new category", new_category_path, class: "add-category-button" %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @category, html: { class: 'custom-form' } do |form| %>
        <div class="form-group mb-3">
          <%= form.text_field :name, class: 'form-control', required: true, placeholder: 'Enter Category Name' %>
        </div>
        <div class="form-group mb-3">
          <%= form.file_field :icon, required: true, class: 'form-control' %>
        </div>
        <%= form.submit(value: 'Save', class: 'submit-category-btn') %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="category-total-cost">
  <h3 class="total-title">Total cost for this category</h3>
  <h3 class="total-expense">$<%= @category_expenses&.sum(:amount) || 0 %></h3>
</div>
<hr>

<div class="card">
  <div class="card-body">
    <div class="category-new">
      <% if @category_expenses.present? %>
        <% @category_expenses.each do |expense| %>
          <div class="card mb-3">
            <div class="card-body d-flex justify-content-between align-items-center">
              <div class="expense-name-time">
                <h2 class="card-title"><%= expense.name %></h2>
                <p class="card-text"><%= "#{expense.created_at.strftime('%d %b, %Y')}" %></p>
              </div>
              <h5 class="card-text">$<%= expense.amount %></h5>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="card-text">No expenses found for this category.</p>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "Add a new transaction", new_category_expense_path(@category), class: "add-transaction-button" %>
</div>

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= expense.category_id %>
  </p>

</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
    <% if expense.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
  
        <ul>
          <% expense.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.label :amount, style: "display: block" %>
      <%= form.text_field :amount %>
    </div>
  
    <div>
      <%= form.label :category_id, style: "display: block" %>
      <%= form.text_field :category_id %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/expenses/new.html.erb
<%= form_with(model: [@category, @expense], url: category_expenses_path(@category), method: :post, remote: true) do |f| %>
  <div class="transaction-name-field text-center">
    <%= f.label :name, 'Name', class: 'tran-name' %>
    <%= f.text_field :name, class: 'transaction-name', required: true, placeholder: 'Enter Name' %>
  </div>

  <div class="transaction-amount-field text-center">
    <%= f.label :amount, 'Amount', class: 'tran-amount' %>
    <%= f.number_field :amount, class: 'transaction-amount', required: true, placeholder: 'Enter Amount' %>
  </div>

  <div class="transaction-category-field text-center">
    <%= f.label :category_id, 'Select a category', class: 'select-category' %>
    <%= f.collection_select(:category_id, current_user.categories, :id, :name, { selected: @expense&.category_id }, { class: 'form-control', required: true }) %>
  </div>

  <div class="save2">
    <%= f.submit 'Save', class: 'add-category-button' %>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice || alert %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <% unless current_page?(root_path) %>
      <% if current_page?(new_category_path) %>
        <%= link_to root_path, class: "navbar-brand d-lg-block d-block" do %>
          <%= image_tag("arrow-left.svg", alt: "Back", class: "back-arrow") %>
        <% end %>
      <% elsif current_page?(categories_path) %>
        <%= link_to categories_path, class: "navbar-brand d-lg-block d-block" do %>
          <%= image_tag("arrow-left.svg", alt: "Back", class: "back-arrow") %>
        <% end %>
      <% elsif defined?(@category) && current_page?(new_category_expense_path(@category)) %>
        <%= link_to category_path(@category), class: "navbar-brand d-lg-block d-block" do %>
          <%= image_tag("arrow-left.svg", alt: "Back", class: "back-arrow") %>
        <% end %>
      <% else %>
        <%= link_to root_path, class: "navbar-brand d-lg-block d-block" do %>
          <%= image_tag("arrow-left.svg", alt: "Back", class: "back-arrow") %>
        <% end %>
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_page?(root_path) %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex">
          <li class="nav-item me-2">
            <span class="nav-link">Category</span>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav d-flex">
          <% if current_page?(new_category_path) %>
            <li class="nav-item me-2">
              <span class="nav-link">Add a new category</span>
            </li>
          <% elsif defined?(@category) && current_page?(new_category_expense_path(@category)) %>
            <li class="nav-item me-2">
              <span class="nav-link">Add a new transaction</span>
            </li>
          <% elsif defined?(@category) && current_page?(category_path(@category)) %>
            <li class="nav-item me-2">
              <span class="nav-link">Transactions</span>
            </li>
          <% end %>
        </ul>
      <% end %>
      <ul class="navbar-nav ms-auto d-flex">
        <% if current_user %>
          <li class="nav-item me-2">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end">
              <li><%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item", data: { turbo_method: :delete } %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item me-2">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item me-2">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>BudgetApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </head>
  <body>
    <header>
    <%= render 'layouts/navbar', category: @category %>
    </header>
    <main>
    <%= render 'layouts/alerts' %> 
    <%= yield %>
    </main>
  </body>
</html>